[package]
name = "boltlang"
version = "0.1.0"
edition = "2024"

[dependencies]
crossbeam-channel = "0.5.15"
dashmap = "6.1.0"
ena = "0.14.3"
filetime = "0.2.27"
fluent-uri = "0.4.1"
lazy_static = "1.5.0"
notify-debouncer-mini = { version = "0.7.0", features = ["crossbeam-channel"] }
rowan = { version = "0.16.1", features = ["serde1"] }
rustc-hash = "2.1.1"
salsa = "0.25.2"
thiserror = "2.0.18"
tracing = "0.1.44"
unicode-ident = "1.0.22"
